# Generated by Django 6.0.3 on 2026-04-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
